version: '3'
networks:
  dev_network:
    driver: bridge
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456@wa
    ports:
      - "3307:3306"
    networks:
      - dev_network
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./:/opt/www/myfirstapp
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=localhost
    networks:
      - dev_network